[workspace]
resolver = "2"
members = [
  # Main crates.
  "src/vqueue",
  "src/vsmtp/vsmtp-auth",
  "src/vsmtp/vsmtp-common",
  "src/vsmtp/vsmtp-config",
  "src/vsmtp/vsmtp-core",
  "src/vsmtp/vsmtp-delivery",
  "src/vsmtp/vsmtp-mail-parser",
  "src/vsmtp/vsmtp-protocol",
  "src/vsmtp/vsmtp-rule-engine",
  "src/vsmtp/vsmtp-server",
  "src/vsmtp/vsmtp-test",
  "src/vsmtp/vsmtp-plugin-vsl",

  # Plugins.

  ## External.
  "src/plugins/vsmtp-plugin-csv",
  "src/plugins/vsmtp-plugin-mysql",
  "src/plugins/vsmtp-plugin-memcached",
  "src/plugins/vsmtp-plugin-ldap",
  "src/plugins/vsmtp-plugin-mongodb",
  "src/plugins/vsmtp-plugin-redis",
  "src/plugins/vsmtp-plugin-dnsxl",
]

exclude = ["fuzz", "benchmarks/stress"]

[profile.release]
opt-level = 2
debug = false
